# Gopherhole builder configuration for Burrow.

# The ASCII art font files used for each heading level.
[fonts]
h1="figlet_graceful.bmf"
h2="simple_octo.bmf"
h3="simple_underline.bmf"
h4="simplest.bmf"
h5="simplest.bmf"
h6="simplest.bmf"

# The built-in spacecookie gopherhole server configuration, formerly fulfilled by a
# spacecookie.json file.
[spacecookie]
# These few below are maybe redundant with the host and port in general!
hostname="localhost"
listenAddr="::"
listenPort=70
# Un-comment line below to switch a specified user when running server.
user="git"
# I wonder if the root directory to serve in spacecookie is redundant considering buildPath in general.
root="/srv/gopher/"

# Blogging-specific configuration.
[phlog]
# The phlog's location inside both the buildPath and sourcePath.
phlogPath="phlog"
tagPath="phlog/tags/"
defaultAuthor="Some Gopher"

[general]
# Everything built will go into this path. All other paths will be relative to
# this path.
buildPath="built"
# The main content files used for building the gopherhole.
sourcePath="burrowsrc"
# The host and port the gopherhole will listen on. This is important due to the nature of
# hosting gophermaps (they need to specify a link's host and port).
host="localhost"
port=7070
# This directive informs the builder to build, not just copy, any file
# with these extensions. Do not include the leading dot. Separate with
# spaces.
buildExtensions="md"
# This helps the builer know which files are menus when it can't read
# the frontmatter or if you don't want to specify in the frontmatter.
# So it'll allow gophermaps to be built out of something like
# *.menu.txt and *.menu.md.
menuExtensionPrefix="menu"
# The format used for timestamps in teh templater.
timeFormat="YYYY-MM-DD"
# Filename used for gophermap indexes (will use the .gophermap specification, which
# gives it more flexibility. See .gophermap in spacecookie documentation).
directoryMapName="index.menu.md"
# Avoid using non-ASCII characters when rendering for terminal compatibility.
asciiSafe=true