#!/bin/sh
git clone /srv/git/gopherhole.git /tmp/gopherhole-clone
cd /tmp/gopherhole-clone
burrow build
pkill burrow
cp /tmp/gopherhole-clone/data/burrow.toml /tmp/burrow.toml
rm -rf /tmp/gopherhole-clone
nohup burrow serve --config /tmp/burrow.toml > /dev/null 2>&1 &