name: Release

# should do this only on master as well?
on: 
  push:
    paths:
      burrow.cabal

jobs:
  # Release job
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Detect version change in cabal
        id: version-check
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            sed -n "s/^version:[[:space:]]\+\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\)\+/\1/p" burrow.cabal
      - name: Make static binary tar.gz
        if: ${{ steps.version-check.outputs.tag }}
        run: make release GHC_VERSION=8.10.4
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: ${{ steps.version-check.outputs.tag }}
        with:
          name: ${{ steps.version-check.outputs.tag }}
          tag_name: ${{ steps.version-check.outputs.tag }}
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            burrow-${{ steps.version-check.outputs.current-version }}-x86_64-linux.tar.gz
            burrow_${{ steps.version-check.outputs.current-version }}_amd64.deb
          body: Unstable/alpha release.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
